services:
  nutri-app:
    image: marcomerini/nutri-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri-app
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG__ChatModel=gpt-4o-mini
      - RAG__EmbeddingModel=text-embedding-3-small
      - RAG__TopK=8
      - RAG__ScoreThreshold=0.25
      - RAG__MaxTokensResposta=2000
      - RAG__ChunkBatchSize=50
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Monitoring/prometheus:/etc/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./Monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./Monitoring/grafana/dashboards:/var/lib/grafana/dashboards
