// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriFlow.Data;

#nullable disable

namespace NutriFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriFlow.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChunksRetrieved")
                        .HasColumnType("int")
                        .HasColumnName("ChunksRetrieved");

                    b.Property<bool>("ConsentimentoLGPD")
                        .HasColumnType("bit")
                        .HasColumnName("ConsentimentoLGPD");

                    b.Property<bool>("DadosPseudonimizados")
                        .HasColumnType("bit")
                        .HasColumnName("DadosPseudonimizados");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Endpoint");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("int")
                        .HasColumnName("LatenciaMs");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<string>("QueryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QueryText");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResponseSummary");

                    b.Property<string>("Sources")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sources");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_AuditLogs_PatientId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.EmbeddingChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChunkText");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ChunkType");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmbeddingJson");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("SourceId");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SourceTable");

                    b.Property<DateTime?>("SourceUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SourceUpdatedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Embeddings_PatientId");

                    b.HasIndex("PatientId", "SourceTable")
                        .HasDatabaseName("IX_Embeddings_PatientId_SourceTable");

                    b.ToTable("Embeddings", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicoesSaude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condicoes_saude");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Altura")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("altura");

                    b.Property<string>("NivelAtividade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nivel_atividade");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Objetivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objetivo");

                    b.Property<decimal?>("PesoAtual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_atual");

                    b.Property<string>("PreferenciasAlimentares")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preferencias_alimentares");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Pacientes_usuario_id");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.PlanoDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaloriasDiarias")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calorias_diarias");

                    b.Property<decimal?>("CarboidratosG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("carboidratos_g");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<decimal?>("GordurasG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("gorduras_g");

                    b.Property<string>("Objetivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objetivo");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("paciente_id");

                    b.Property<decimal?>("ProteinasG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("proteinas_g");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_Planos_Dieta_paciente_id");

                    b.ToTable("Planos_Dieta", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Progresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anotacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anotacoes");

                    b.Property<decimal?>("CinturaCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cintura_cm");

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registro");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("paciente_id");

                    b.Property<decimal?>("PercentualGordura")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual_gordura");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso");

                    b.Property<decimal?>("QuadrilCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("quadril_cm");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_Progresso_paciente_id");

                    b.ToTable("Progresso", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Refeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calorias")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calorias");

                    b.Property<string>("Alimentos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alimentos");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("horario");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("int")
                        .HasColumnName("plano_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("IX_Refeicoes_plano_id");

                    b.ToTable("Refeicoes", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anotacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTime?>("DataSessao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_sessao");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("paciente_id");

                    b.Property<decimal?>("PesoSessao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_sessao");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_Sessoes_paciente_id");

                    b.ToTable("Sessoes", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Models.Paciente", b =>
                {
                    b.HasOne("NutriFlow.Models.Usuario", "Usuario")
                        .WithMany("Pacientes")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Pacientes_Usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NutriFlow.Models.PlanoDieta", b =>
                {
                    b.HasOne("NutriFlow.Models.Paciente", "Paciente")
                        .WithMany("PlanosDieta")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_Planos_Dieta_Pacientes_paciente_id");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriFlow.Models.Progresso", b =>
                {
                    b.HasOne("NutriFlow.Models.Paciente", "Paciente")
                        .WithMany("Progressos")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_Progresso_Pacientes_paciente_id");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriFlow.Models.Refeicao", b =>
                {
                    b.HasOne("NutriFlow.Models.PlanoDieta", "PlanoDieta")
                        .WithMany("Refeicoes")
                        .HasForeignKey("PlanoId")
                        .HasConstraintName("FK_Refeicoes_Planos_Dieta_plano_id");

                    b.Navigation("PlanoDieta");
                });

            modelBuilder.Entity("NutriFlow.Models.Sessao", b =>
                {
                    b.HasOne("NutriFlow.Models.Paciente", "Paciente")
                        .WithMany("Sessoes")
                        .HasForeignKey("PacienteId")
                        .HasConstraintName("FK_Sessoes_Pacientes_paciente_id");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriFlow.Models.Paciente", b =>
                {
                    b.Navigation("PlanosDieta");
                    b.Navigation("Progressos");
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("NutriFlow.Models.PlanoDieta", b =>
                {
                    b.Navigation("Refeicoes");
                });

            modelBuilder.Entity("NutriFlow.Models.Usuario", b =>
                {
                    b.Navigation("Pacientes");
                });

#pragma warning restore 612, 618
        }
    }
}
